-- MySQL Script generated by MySQL Workbench
-- Sex 05 Dez 2014 10:05:12 BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area_atuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area_atuacao` (
  `id_area_atuacao` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_area_atuacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidade` (
  `id_unidade` INT NOT NULL AUTO_INCREMENT,
  `area_atuacao_id` INT NOT NULL,
  PRIMARY KEY (`id_unidade`),
  INDEX `fk_unidade_area_atuacao1_idx` (`area_atuacao_id` ASC),
  CONSTRAINT `fk_unidade_area_atuacao1`
    FOREIGN KEY (`area_atuacao_id`)
    REFERENCES `mydb`.`area_atuacao` (`id_area_atuacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obra` (
  `id_obra` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria_id` INT(11) NOT NULL,
  `unidade_id` INT(11) NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` TEXT NULL,
  `endereco` VARCHAR(255) NULL,
  `tipo` VARCHAR(100) NOT NULL,
  `ordem_servico` VARCHAR(45) NULL,
  `data_iniciio` DATE NULL,
  `previsao` DATE NULL,
  `percent_exec` VARCHAR(45) NULL,
  `situacao` VARCHAR(45) NULL,
  `bairros` VARCHAR(255) NULL,
  `orgaos` VARCHAR(255) NULL,
  `origem_OP` TINYINT NULL,
  `latitude` DECIMAL(16,14) NOT NULL,
  `longitude` DECIMAL(16,14) NOT NULL,
  `area_atuacao` VARCHAR(255) NULL,
  `unidade` VARCHAR(255) NULL,
  `data_cadastro` DATETIME NULL,
  PRIMARY KEY (`id_obra`),
  INDEX `fk_tb_obras_tb_categoria_idx` (`categoria_id` ASC),
  INDEX `fk_obra_unidade1_idx` (`unidade_id` ASC),
  CONSTRAINT `fk_tb_obras_tb_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obra_unidade1`
    FOREIGN KEY (`unidade_id`)
    REFERENCES `mydb`.`unidade` (`id_unidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresa` (
  `id_empresa` INT(11) NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(18) NOT NULL,
  `razao_social` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recurso` (
  `id_recurso` INT(11) NOT NULL,
  `descricao` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_recurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`licitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`licitacao` (
  `id_licitacao` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `contrato` VARCHAR(45) NULL,
  `data_cadastro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_licitacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responsavel` (
  `id_responsavel` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_responsavel` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_responsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obra_licitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obra_licitacao` (
  `obra_id` INT(11) NOT NULL,
  `licitacao_id` INT(11) NOT NULL,
  `empresa_id` INT(11) NOT NULL,
  `responsavel_id` INT(11) NOT NULL,
  PRIMARY KEY (`obra_id`, `licitacao_id`, `empresa_id`, `responsavel_id`),
  INDEX `fk_licitacao_has_obra_obra1_idx` (`obra_id` ASC),
  INDEX `fk_licitacao_has_obra_licitacao1_idx` (`licitacao_id` ASC),
  INDEX `fk_licitacao_has_obra_empresa1_idx` (`empresa_id` ASC),
  INDEX `fk_licitacao_obra_responsavel1_idx` (`responsavel_id` ASC),
  CONSTRAINT `fk_licitacao_has_obra_licitacao1`
    FOREIGN KEY (`licitacao_id`)
    REFERENCES `mydb`.`licitacao` (`id_licitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_licitacao_has_obra_obra1`
    FOREIGN KEY (`obra_id`)
    REFERENCES `mydb`.`obra` (`id_obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_licitacao_has_obra_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `mydb`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_licitacao_obra_responsavel1`
    FOREIGN KEY (`responsavel_id`)
    REFERENCES `mydb`.`responsavel` (`id_responsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bairro` (
  `id_bairro` INT(11) NOT NULL AUTO_INCREMENT,
  `zona` VARCHAR(45) NULL,
  `regiao_od` VARCHAR(45) NULL,
  `nome_bairro` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_bairro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obra_recursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obra_recursos` (
  `obra_id` INT(11) NOT NULL,
  `recurso_id` INT(11) NOT NULL,
  `valor` VARCHAR(45) NULL,
  PRIMARY KEY (`obra_id`, `recurso_id`),
  INDEX `fk_obra_has_recurso_recurso1_idx` (`recurso_id` ASC),
  INDEX `fk_obra_has_recurso_obra1_idx` (`obra_id` ASC),
  CONSTRAINT `fk_obra_has_recurso_obra1`
    FOREIGN KEY (`obra_id`)
    REFERENCES `mydb`.`obra` (`id_obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_obra_has_recurso_recurso1`
    FOREIGN KEY (`recurso_id`)
    REFERENCES `mydb`.`recurso` (`id_recurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orgaos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orgaos` (
  `id_orgao` INT(11) NOT NULL,
  PRIMARY KEY (`id_orgao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obra_bairros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obra_bairros` (
  `obra_id` INT(11) NOT NULL,
  `bairro_id` INT(11) NOT NULL,
  PRIMARY KEY (`obra_id`, `bairro_id`),
  INDEX `fk_bairro_has_obra_obra1_idx` (`obra_id` ASC),
  INDEX `fk_bairro_has_obra_bairro1_idx` (`bairro_id` ASC),
  CONSTRAINT `fk_bairro_has_obra_bairro1`
    FOREIGN KEY (`bairro_id`)
    REFERENCES `mydb`.`bairro` (`id_bairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bairro_has_obra_obra1`
    FOREIGN KEY (`obra_id`)
    REFERENCES `mydb`.`obra` (`id_obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`obra_orgaos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obra_orgaos` (
  `obra_id` INT(11) NOT NULL,
  `orgao_id` INT(11) NOT NULL,
  PRIMARY KEY (`obra_id`, `orgao_id`),
  INDEX `fk_orgaos_has_obra_obra1_idx` (`obra_id` ASC),
  INDEX `fk_orgaos_has_obra_orgaos1_idx` (`orgao_id` ASC),
  CONSTRAINT `fk_orgaos_has_obra_orgaos1`
    FOREIGN KEY (`orgao_id`)
    REFERENCES `mydb`.`orgaos` (`id_orgao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orgaos_has_obra_obra1`
    FOREIGN KEY (`obra_id`)
    REFERENCES `mydb`.`obra` (`id_obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(180) NOT NULL,
  `senha` VARCHAR(128) NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `perfil_id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_perfil1_idx` (`perfil_id_perfil` ASC),
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_id_perfil`)
    REFERENCES `mydb`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
